FROM reposc.cloud.test/cmcf-harbor-uat/openjdk8:v1

RUN useradd --create-home cmcf && mkdir cmcf-cp && chown cmcf:cmcf /cmcf-cp

USER cmcf

ADD start/target/cmcf-cp.jar /cmcf-cp/cmcf-cp.jar
ADD devops/start.sh /cmcf-cp/start.sh

WORKDIR /cmcf-cp

CMD ["bash", "start.sh"]